node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test dependency') {
     sh 'docker run -v $PWD:/scan licensefinder/license_finder /bin/bash -lc \'cd scan; ls; license_finder\' '
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("yongzecheu/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
