node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test dependency') {
      sh 'docker run --rm --volume-from=$HOSTNAME -w ${WORKSPACE} licensefinder/license_finder /bin/bash -lc \'ls; license_finder\' '
   }
   
   stage('test gitleaks') {
      sh 'docker run --rm --volume-from=$HOSTNAME -w ${WORKSPACE} zricethezav/gitleaks:latest --repo-path=${WORKSPACE} '
   }
   
}
