node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test dependency') {
     def myTestContainer = docker.image('licensefinder/license_finder:latest')
     myTestContainer.pull()
      myTestContainer.inside("-v ${PWD}:/scanRepo") {
          sh 'license_finder'                     
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("yongzecheu/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
